### ISSUE TITLE
trouble running CamusJob

### ISSUE THREAD

**Issue by shlomitub28** [linkedin/camus#170]
hi guys,
trying to run camus example jar fails 

 java -cp target/camus-example-0.1.0-SNAPSHOT-shaded.jar:target/camus-example-0.1.0-SNAPSHOT.jar:/usr/lib/hadoop-hdfs/* com.linkedin.camus.etl.kafka.CamusJob -P target/classes/camus.properties
[NativeCodeLoader] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[CamusJob] - Dir Destination set to: /common/camus/topics
[CamusJob] - Previous execution: hdfs://r-aa-fatty09-b0:8020/common/camus/exec/history/2015-02-08-09-12-57
[CamusJob] - New execution temp location: /camus/exec/2015-02-08-13-07-53
log4j:ERROR Attempted to append to closed appender named [CamusConsole].
log4j:ERROR Attempted to append to closed appender named [CamusConsole].
[CamusJob] - Fetching metadata from broker r-aa-fatty10:9092 with client id camus for 0 topic(s) []
[CamusJob] - Discarding topic : test-rep-one
[CamusJob] - Discarding topic : my-replicated-topic
[CamusJob] - Discarding topic : test
[CamusJob] - failed to create decoder
com.linkedin.camus.coders.MessageDecoderException: com.linkedin.camus.coders.MessageDecoderException: java.lang.InstantiationException: com.linkedin.camus.example.schemaregistry.DummySchemaRegistry
        at com.linkedin.camus.etl.kafka.coders.MessageDecoderFactory.createMessageDecoder(MessageDecoderFactory.java:29)
        at com.linkedin.camus.etl.kafka.mapred.EtlInputFormat.createMessageDecoder(EtlInputFormat.java:391)
        at com.linkedin.camus.etl.kafka.mapred.EtlInputFormat.getSplits(EtlInputFormat.java:256)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:491)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:508)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:392)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1268)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1265)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1265)
        at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:335)
        at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:563)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at com.linkedin.camus.etl.kafka.CamusJob.main(CamusJob.java:518)
Caused by: com.linkedin.camus.coders.MessageDecoderException: java.lang.InstantiationException: com.linkedin.camus.example.schemaregistry.DummySchemaRegistry

as understood im other threads , there are issues with the DummyDecoder.
thank you

**Comment by shlomitub28** [comment]
i am closing this issue. succeeded running with Json decoder.
