### ISSUE TITLE
YarnRuntimeException: java.io.FileNotFoundException File does not exist: job.splitmetainfo

### ISSUE THREAD

**Issue by seregasheypak** [linkedin/camus#223]
Hi, trying to run Camus on CDH5 5.3.2 and Yarn
Getting exception while application master tries to start

Here is what CamusJob outputs to log:
```
JobSubmitter] - number of splits:40
[deprecation] - mapred.output.compress is deprecated. Instead, use mapreduce.output.fileoutputformat.compress
[deprecation] - mapred.output.compression.codec is deprecated. Instead, use mapreduce.output.fileoutputformat.compress.codec
[deprecation] - mapred.map.tasks.speculative.execution is deprecated. Instead, use mapreduce.map.speculative
[deprecation] - mapred.reduce.tasks.speculative.execution is deprecated. Instead, use mapreduce.reduce.speculative
[deprecation] - mapred.output.compression.type is deprecated. Instead, use mapreduce.output.fileoutputformat.compress.type
[deprecation] - mapred.job.queue.name is deprecated. Instead, use mapreduce.job.queuename
[JobSubmitter] - Submitting tokens for job: job_1430983074484_0039
[JobSubmitter] - Kind: YARN_AM_RM_TOKEN, Service: , Ident: (org.apache.hadoop.yarn.security.AMRMTokenIdentifier@64cd68e9)
[JobSubmitter] - Kind: RM_DELEGATION_TOKEN, Service: 10.66.62.141:8032,10.66.62.146:8032, Ident: (owner=devops, renewer=oozie mr token, realUser=oozie, issueDate=1430986158581, maxDate=1431590958581, sequenceNumber=71414, masterKeyId=112)
[YarnClientImpl] - Submitted application application_1430983074484_0039
[Job] - The url to track the job: http://prod-node0168.myhost.ru:8088/proxy/application_1430983074484_0039/
[Job] - Running job: job_1430983074484_0039
```

I goto ` http://prod-node0168.myhost.ru:8088/proxy/application_1430983074484_0039/`
and see that it fails to start apllicationMaster:

```
015-05-07 11:09:50,722 WARN [main] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: Job init failed
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.io.FileNotFoundException: File does not exist: hdfs://nameservice1/user/devops/.staging/job_1430983074484_0039/job.splitmetainfo
	at org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl$InitTransition.createSplits(JobImpl.java:1566)
	at org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl$InitTransition.transition(JobImpl.java:1430)
	at org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl$InitTransition.transition(JobImpl.java:1388)
	at org.apache.hadoop.yarn.state.StateMachineFactory$MultipleInternalArc.doTransition(StateMachineFactory.java:385)
	at org.apache.hadoop.yarn.state.StateMachineFactory.doTransition(StateMachineFactory.java:302)
	at org.apache.hadoop.yarn.state.StateMachineFactory.access$300(StateMachineFactory.java:46)
	at org.apache.hadoop.yarn.state.StateMachineFactory$InternalStateMachine.doTransition(StateMachineFactory.java:448)
	at org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl.handle(JobImpl.java:996)
	at org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl.handle(JobImpl.java:138)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$JobEventDispatcher.handle(MRAppMaster.java:1272)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceStart(MRAppMaster.java:1045)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$1.run(MRAppMaster.java:1478)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1474)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1407)
Caused by: java.io.FileNotFoundException: File does not exist: hdfs://nameservice1/user/devops/.staging/job_1430983074484_0039/job.splitmetainfo
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1093)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1085)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1085)
	at org.apache.hadoop.mapreduce.split.SplitMetaInfoReader.readSplitMetaInfo(SplitMetaInfoReader.java:51)
	at org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl$InitTransition.createSplits(JobImpl.java:1561)
	... 17 more
```

**Comment by brahmareddybattula** [comment]
any solution for this..?

**Comment by seregasheypak** [comment]
I solved it configuring yarn. The problem was in uberisation, as I remember.

**Comment by brahmareddybattula** [comment]
same we are facing , when we use WebHCat .. can you please elaborate your solution..? and our's is secure cluster..

**Comment by brahmareddybattula** [comment]
same we are facing , when we use WebHCat .. can you please elaborate your solution..? and our's is secure cluster..
