### ISSUE TITLE
Camus running on remote node - java.io.IOException: No FileSystem for scheme: file

### ISSUE THREAD

**Issue by ctippur** [linkedin/camus#84]
I am using CDH4 for hadoop standalone cluster. This runs on a different node than the one I am trying to run camus.

I get the following error when I run camus:

PriviledgedActionException as:ctippur (auth:SIMPLE) cause:java.io.IOException: No FileSystem for scheme: file
Exception in thread "main" java.io.IOException: No FileSystem for scheme: file
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2298)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2305)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:89)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2344)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2326)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:353)
	at org.apache.hadoop.fs.FileSystem.getLocal(FileSystem.java:324)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:2003)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1971)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1936)
	at org.apache.hadoop.mapred.JobClient.copyAndConfigureFiles(JobClient.java:904)
	at org.apache.hadoop.mapred.JobClient.copyAndConfigureFiles(JobClient.java:774)
	at org.apache.hadoop.mapred.JobClient.access$400(JobClient.java:178)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:991)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:976)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:976)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:582)
	at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:318)
	at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:646)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.linkedin.camus.etl.kafka.CamusJob.main(CamusJob.java:610)

I am running camus as below:

java -Xss256m -cp camus-api/target/*:camus-etl-kafka/target/camus-etl-kafka-0.1.0-SNAPSHOT.jar:lib/httpclient-4.3.4.jar:lib/kafka-0.7.2.jar:lib/zkclient-0.1.jar:lib/avro-tools-1.7.3.jar::camus-example/target/camus-example-0.1.0-SNAPSHOT.jar:camus-example/target/camus-example-0.1.0-SNAPSHOT-shaded.jar:camus-example/target/camus-example-0.1.0-SNAPSHOT-tests.jar:/home/ctippur/.m2/repository/org/apache/hadoop/hadoop-client/2.0.0-mr1-cdh4.7.0/hadoop-client-2.0.0-mr1-cdh4.7.0.jar:/contrib/capacity-scheduler/* com.linkedin.camus.etl.kafka.CamusJob  -P camus.1.txt

**Comment by ChicoQ** [comment]
ERROR security.UserGroupInformation: PriviledgedActionException as:hadoop (auth:SIMPLE) cause:java.io.IOException
Exception in thread "main" java.io.IOException
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:317)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobCounters(ClientServiceDelegate.java:337)
	at org.apache.hadoop.mapred.YARNRunner.getJobCounters(YARNRunner.java:476)
	at org.apache.hadoop.mapreduce.Job$8.run(Job.java:757)
	at org.apache.hadoop.mapreduce.Job$8.run(Job.java:754)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
	at org.apache.hadoop.mapreduce.Job.getCounters(Job.java:754)
	at com.linkedin.camus.etl.kafka.reporter.TimeReporter.report(TimeReporter.java:97)
	at com.linkedin.camus.etl.kafka.CamusJob.createReport(CamusJob.java:497)
	at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:372)
	at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:563)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.linkedin.camus.etl.kafka.CamusJob.main(CamusJob.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:208)
